### ISSUE TITLE
How do I train myself with labeled data sets?

### ISSUE THREAD

**Issue by zsffuture** [Picsart-AI-Research/MI-GAN#1]
Thank you very much for your work. I plan to train my own data set. The current data set is the original picture 'images' and the labels' masks' made by me, but the masks you gave me are data/places2/train_512, so is the train_512 folder corresponding to the original picture? I see that your mask code is randomly generated, so I would like to ask, how do I train myself with labeled data sets? How to configure the file? How do you put the data set?

**Comment by AndranikSargsyan** [comment]
Yes, `train_512` is the folder containing original images, and the masks are generated randomly on the fly. If you want to train using pre-defined masks, you should add another type of `Formatter` as in [here](https://github.com/Picsart-AI-Research/MI-GAN/blob/main/lib/data_factory/ds_places2.py#L187), which will return the corresponding pre-defined mask for each image, instead of randomly generated one. Then, you should modify the config file (see [here](https://github.com/Picsart-AI-Research/MI-GAN/blob/main/configs/dataset/places2.yaml#L42)) to use that specific type of Formatter that you added.
